### ISSUE TITLE
mcombo: ";" after last item not removed

### ISSUE THREAD

**Issue by species** [TransforMap/iD#18]
if you check some items in a mcombo box, and uncheck them afterwards, the semicolon (";") is not removed after the last item.

**Comment by thoka** [comment]
I fixed that but thinking about it, it would be better to have ; at the end
until the widget looses fokus.
The usual action will be to switch to a different entry or to add an other.
When adding by typing, a semicolon would help to start a new value
automatically.

But maybe using ; and having one value is 9ties style anyway and we should
render the individual options in separate divs, like select2 does.
https://select2.github.io/examples.html

**Comment by species** [comment]
I think removing it when the widget looses fokus would be the best solution!

**Comment by species** [comment]
a simple .replace(/;$/,""); in set_value() in file d3.mcombobox.js did it.
