### ISSUE TITLE
Add missing tags (from degrowth)

### ISSUE THREAD

**Issue by gandhiano** [TransforMap/iD#19]
After discussing with Silke on a proposal coming from Corinna/Nina/Andrea (Degrowth community), two tags should already be added:

```
Key: Identity
Value: degrowth
Description: Organisations and projects that identify themselves as being part of degrowth and its synonyms in different languages as for instance décroissance.
Label: degrowth
```

```
key: interaction
value: sharing
description: Here you can share material (tools, books, etc.) and immaterial (time, knowledge, ideas) matters.
label: by way of sharing
```

**Comment by species** [comment]
identity=degrowth is included in our iD.

interaction=sharing overlaps with other values from interaction, e.g. bartering and cousing. Still waiting for an answer from Silke about this item.

**Comment by species** [comment]
added it, but still no text to distinguish it clearly from the others :-/
