### ISSUE TITLE
dist/ not serveable on editor.transformap.co

### ISSUE THREAD

**Issue by species** [TransforMap/iD#20]
content of dist/ is not included in the repository, so the dist/ - version is not functioning. (We are still serving the version with >200 single .js files)

cause: "make" gets not executed, if you push to dokku@apps.ecobytes.net:id.

please include "make" in the deploy-script, then point editor.transformap.co/ to editor.transformap.co/dist/ .

**Comment by almereyda** [comment]
Is this a duplicate of #1 ? Also read the deploy script mentioned there.

I will adopt the deploy script soon, but I'd rather have `deploy` run make, commit these changes to the git tree and only then, after comparison, push to `gh-pages`.

**Comment by species** [comment]
I've created a new branch named "dist", copied everything from dist/ here and pushed it 
to apps.ecobytes.net:id, so editor.transformap.co is now serving the dist/ variant.

how to do this, is documented in the README.md.

**Comment by thoka** [comment]
Thank you for all this work ...
