### ISSUE TITLE
add CSA POIs

### ISSUE THREAD

**Issue by species** [TransforMap/iD#27]
farm_boxes=pickup/source/source_and_pickup
https://wiki.openstreetmap.org/wiki/Proposed_features/Farm_boxes

**Comment by species** [comment]
fixed with d9e4cdac203837ee3da0209ef06a0624d082247f

**Comment by gandhiano** [comment]
I don't know exactly where this was discussed, but farm or vegetables boxes are not an appropriate POI for most CSAs in Germany. Rather, there are "farms" and "delivery places" (where the whole produce is brought and people can come to pickup). These are relatively stable places, although of course bound to change from time to time (but that's not different from many other information being mapped OSM). Some of this is represented here: https://ernte-teilen.org/

**Comment by species** [comment]
Look here: https://wiki.openstreetmap.org/wiki/Proposed_features/Farm_boxes
the farm_boxes=\* tag was chosen because CSA's are not called "csa" in the whole world, and a key understandable by everyone was needed.
OSM keys don't represent their literal meaning in a lot of cases, e.g. steps are a subtype of "highway".
