### ISSUE TITLE
Implement Multiselect-Box

### ISSUE THREAD

**Issue by species** [TransforMap/iD#5]
For adding values with multiple values using the ";" (semicolon) - separator, e.g. for the "cuisine" value.

**Comment by thoka** [comment]
should work with #15

**Comment by species** [comment]
works also in dist/ after 0879161 ,  c5851c8  and  2e2b68f .

**Comment by species** [comment]
parsing multiple values is still a problem, have to rework the whole code, of d3.mcombobox also :-/
working on it.

**Comment by species** [comment]
It's live now, maybe we should start working on a official pull-request do openstreetmap/iD
